### ISSUE TITLE
boost conflicts with matlab

### ISSUE THREAD

**Issue by march1993** [mriesch-tum/mbsolve#19]
Matlab runtime has its own boost library while mbsolve-tool uses boost from system vendor. What makes it worse is that matlab runtime does not provide boost header files and compilation flags, which means even by using the same version of boost, crash still happens.

Possible solution: use boost bcp to rename boost namespace.

**Comment by mriesch-tum** [comment]
Thanks for the bug report. Can you give some additional information (compiler version, Boost version, MATLAB version/MATLAB's boost version) and the crash log/error message?

However, in near future we plan to use an open data format (e.g. HDF5) to export the results and get rid of the MATLAB dependency, so the issue may resolve itself.

**Comment by mriesch-tum** [comment]
The matlab writer has been removed from mbsolve. Closing this one...
